### ISSUE TITLE
Order Management

### ISSUE THREAD

**Issue by freshmenyuan** [JSRedTeam/oneStep#6]
- [ ] Shopping Cart Page
  -  [ ] list all chosen dishes #7
  -  [ ] checkout button #12
  -  [ ] remove button for every chosen dishes #17 
  -  [ ] modify the quantity #18
-  [ ] Delivery Info Page
  -  [ ] Select or input address, name, phone number, date time #19
  -  [ ] Delivery Info Page - validation (date-time) #24
  -  [ ] Pay button #20
-  [ ] Receipt Page 
  -  [ ] list order information which just ordered #21 
-  [ ] Me page
  -  [ ] Order history #22 
- [ ] Order Schema Defination #23
